services: docker
language: bash
addons:
  apt:
    packages:
      - python-pip

env:
  global:
    - PACKAGE_NAME=mcl_3dl_msgs
  matrix:
    - ROS_DISTRO_TARGET=kinetic
    - ROS_DISTRO_TARGET=melodic
branches:
  only:
    - master

before_install:
  - pip install --user gh-pr-comment

install: true

script:
  - docker build
    -t mcl-3dl-msgs
    -f .travis/Dockerfile
    --pull=true ${TRAVIS_BUILD_DIR}
    --build-arg ROS_DISTRO=${ROS_DISTRO_TARGET}
    || (gh-pr-comment "[#${TRAVIS_BUILD_NUMBER}] FAILED on ${ROS_DISTRO_TARGET}" "docker build failed"; false)
  - docker run --rm -it
    -e TRAVIS_PULL_REQUEST
    -e TRAVIS_PULL_REQUEST_SLUG
    -e TRAVIS_BOT_GITHUB_TOKEN
    -e GITHUB_API_URL_BASE
    -e TRAVIS_BUILD_NUMBER
    mcl-3dl-msgs /catkin_ws/src/${PACKAGE_NAME}/.travis/test.sh
